#!/bin/bash
##############################################################################
#  ELELAB_aggregate_RosettaDDGPrediction.sh  –  aggregate the results of the 
#                      RosettaDDGPrediction saturation run.
#
#  HOW TO USE
#  
#  4.  Run    bash ELELAB_aggregate_RosettaDDGPrediction.sh          – or –
#             qsub ELELAB_aggregate_RosettaDDGPrediction.sh
##############################################################################

source /programs/sbgrid.shrc
source /wynton/home/craik/kjander/ddg/RosettaDDGPrediction/ddg/bin/activate

# Automatically detect the mutinfo.txt file in the flexddg directory
MUTINFO_PATH="$(pwd)/flexddg/mutinfo.txt"

# Check if the mutinfo.txt file exists
if [ ! -f "$MUTINFO_PATH" ]; then
    echo "Error: mutinfo.txt not found at $MUTINFO_PATH"
    echo "Please ensure you are running this script from the run directory (not the flexddg directory)"
    exit 1
fi

echo "Using mutinfo.txt at: $MUTINFO_PATH"

# Recreate the residue types file that would have been generated by generate_mutation_inputs.py
# This file contains the standard 20 amino acids used for saturation mutagenesis
RESLIST_FILE="$(pwd)/residues.txt"
echo "Creating residue types file for mutatex conversion..."

# Generate the standard 20 AA list in the same order as generate_mutation_inputs.py
AA_TYPES="ACDEFGHIKLMNPQRSTVWY"
> "$RESLIST_FILE"  # Clear/create the file
for (( i=0; i<${#AA_TYPES}; i++ )); do
    echo "${AA_TYPES:$i:1}" >> "$RESLIST_FILE"
done

echo "Generated standard 20 AA reslist file: $RESLIST_FILE"

rosetta_ddg_aggregate \
    -cr /wynton/home/craik/kjander/ddg/RosettaDDGPrediction/RosettaDDGPrediction/config_run/ddg_kja_prod_agg35.yaml \
    -ca /wynton/home/craik/kjander/ddg/RosettaDDGPrediction/RosettaDDGPrediction/config_aggregate/aggregate.yaml \
    -cs /wynton/home/craik/kjander/ddg/RosettaDDGPrediction/RosettaDDGPrediction/config_settings/nompi.yaml \
    --mutatex-convert \
    --mutatex-reslistfile "$RESLIST_FILE" \
    -mf "$MUTINFO_PATH"